name: Windows C CI Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v4

    - name: 設定 MSVC 編譯環境
      uses: ilammy/msvc-dev-cmd@v1

    - name: 編譯 main.c
      # 告訴 GitHub Actions 先切換到 for_windows 資料夾再執行 cl.exe
      working-directory: ./for_windows
      run: cl.exe /Fe:test_app.exe main.c

    - name: 執行編譯出來的程式
      # 同樣要在 for_windows 資料夾底下執行剛剛產生出來的 test_app.exe
      working-directory: ./for_windows
      run: .\test_app.exe
